/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'proposal-files': ProposalFile;
    'proposal-upload-assets': ProposalUploadAsset;
    'proposal-requests': ProposalRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'proposal-files': ProposalFilesSelect<false> | ProposalFilesSelect<true>;
    'proposal-upload-assets': ProposalUploadAssetsSelect<false> | ProposalUploadAssetsSelect<true>;
    'proposal-requests': ProposalRequestsSelect<false> | ProposalRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'ru' | 'ru'[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Для новых страниц из админки выбирайте “Пользовательская страница”.
   */
  routeType: 'custom' | 'system';
  pageKey?:
    | ('home' | 'solutions' | 'pricing' | 'get-proposal' | 'concepts' | 'for-startups' | 'for-partners' | 'method')
    | null;
  /**
   * Без префикса локали. Например: test или services/fintech-ui
   */
  slug?: string | null;
  /**
   * Человекочитаемое название страницы для редакторов.
   */
  internalName: string;
  metaTitle?: string | null;
  metaDescription?: string | null;
  layout: (
    | {
        eyebrow?: string | null;
        /**
         * Fallback title. Used if titleRows are not filled. You can keep it for quick editing, but titleRows give a closer match to the original hero styling.
         */
        title?: string | null;
        /**
         * Recommended for pixel-closer hero styling. Each row can contain several segments with different tone.
         */
        titleRows?:
          | {
              segments: {
                text: string;
                tone?: ('default' | 'emphasis' | 'muted') | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        description?: string | null;
        /**
         * Optional small supporting note under the main description.
         */
        supportingNote?: string | null;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        primaryButtonLabel?: string | null;
        primaryPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        secondaryButtonLabel?: string | null;
        secondaryPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        desktopBadgeLabel?: string | null;
        mobileBadgeLabel?: string | null;
        desktopImageSource?: ('url' | 'upload') | null;
        desktopImageAlt?: string | null;
        desktopImageUrl?: string | null;
        desktopImage?: (number | null) | Media;
        mobileImageSource?: ('url' | 'upload') | null;
        mobileImageAlt?: string | null;
        mobileImageUrl?: string | null;
        mobileImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow: string;
        title: string;
        /**
         * Optional supporting paragraph under the title. Used in Arabic version in the original design.
         */
        description?: string | null;
        items: {
          variant: 'icon' | 'step';
          icon?: ('trendingUp' | 'trophy' | 'code') | null;
          /**
           * Small top label. For RU this is EN word (Raise/Win/Build). Optional for step cards.
           */
          kicker?: string | null;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'valueHome';
      }
    | {
        displayMode: 'full' | 'compact';
        eyebrow: string;
        title: string;
        subheadline: string;
        videoLabel: string;
        durationLabel: string;
        metaBadges?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        timeline: {
          number: string;
          label: string;
          description: string;
          id?: string | null;
        }[];
        highlightsTitle: string;
        highlights: {
          label: string;
          id?: string | null;
        }[];
        ctaTitle: string;
        ctaSubtext: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        videoSource: 'url' | 'upload';
        /**
         * Можно использовать прямую ссылку на mp4/webm.
         */
        videoUrl?: string | null;
        videoFile?: (number | null) | Media;
        posterSource: 'url' | 'upload';
        posterUrl?: string | null;
        posterMedia?: (number | null) | Media;
        posterAlt?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoWalkthroughHome';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          icon: 'fileText' | 'users' | 'gitBranch' | 'layoutGrid' | 'palette' | 'mousePointer' | 'layers' | 'fileCheck';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'deliverablesHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyHome';
      }
    | {
        sectionId?: string | null;
        eyebrow: string;
        title: string;
        problemLabel: string;
        solutionLabel: string;
        resultLabel: string;
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        items: {
          title: string;
          problem: string;
          solution: string;
          result: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'audienceHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        challengeLabel: string;
        structuredLabel: string;
        deliveredLabel: string;
        viewConceptsLabel: string;
        conceptsPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        previousAriaLabel: string;
        nextAriaLabel: string;
        items: {
          title: string;
          badge: string;
          challenge: string;
          structured: string;
          delivered: string;
          imageSource?: ('url' | 'upload') | null;
          imageAlt?: string | null;
          imageUrl?: string | null;
          imageMedia?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'conceptsHome';
      }
    | {
        sectionId?: string | null;
        eyebrow: string;
        title: string;
        description: string;
        items: {
          number: string;
          title: string;
          description: string;
          details: {
            label: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'methodHome';
      }
    | {
        sectionId?: string | null;
        eyebrow: string;
        title: string;
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        featuredBadge: string;
        items: {
          name: string;
          price: string;
          timeline: string;
          description: string;
          featured?: boolean | null;
          includes: {
            label: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingHome';
      }
    | {
        sectionId?: string | null;
        title: string;
        description: string;
        steps: {
          icon: 'fileText' | 'mail' | 'checkCircle';
          title: string;
          description: string;
          id?: string | null;
        }[];
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'proposalHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          subtitle: string;
          imageSource?: ('url' | 'upload') | null;
          alt: string;
          imageUrl?: string | null;
          imageMedia?: (number | null) | Media;
          id?: string | null;
        }[];
        bottomNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'samplePreviewHome';
      }
    | {
        items: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustHome';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqHome';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'finalCtaHome';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        note: string;
        tags: {
          label: string;
          id?: string | null;
        }[];
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        imageSource?: ('url' | 'upload') | null;
        imageAlt: string;
        imageUrl?: string | null;
        imageMedia?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroSolutions';
      }
    | {
        title: string;
        description: string;
        items: {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'positioningIntroSolutions';
      }
    | {
        eyebrow: string;
        learnMoreLabel: string;
        items: {
          anchorId: string;
          title: string;
          subtitle: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gridSolutions';
      }
    | {
        whenRelevantLabel: string;
        whatWeClarifyLabel: string;
        whatClientReceivesLabel: string;
        items: {
          anchorId: string;
          title: string;
          intro: string;
          whenRelevant: {
            label: string;
            id?: string | null;
          }[];
          whatWeClarify: {
            label: string;
            id?: string | null;
          }[];
          whatClientReceives: {
            label: string;
            id?: string | null;
          }[];
          primaryButtonLabel: string;
          primaryPageKey:
            | 'home'
            | 'solutions'
            | 'pricing'
            | 'get-proposal'
            | 'concepts'
            | 'for-startups'
            | 'for-partners'
            | 'method';
          secondaryButtonLabel?: string | null;
          secondaryPageKey?:
            | (
                | 'home'
                | 'solutions'
                | 'pricing'
                | 'get-proposal'
                | 'concepts'
                | 'for-startups'
                | 'for-partners'
                | 'method'
              )
            | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'detailsSolution';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          subtitle: string;
          imageSource?: ('url' | 'upload') | null;
          alt: string;
          imageUrl?: string | null;
          imageMedia?: (number | null) | Media;
          id?: string | null;
        }[];
        bottomNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'clientArtifactsSolutions';
      }
    | {
        eyebrow: string;
        title: string;
        challengeLabel: string;
        resultLabel: string;
        items: {
          title: string;
          challenge: string;
          result: string;
          ctaLabel: string;
          ctaPageKey:
            | 'home'
            | 'solutions'
            | 'pricing'
            | 'get-proposal'
            | 'concepts'
            | 'for-startups'
            | 'for-partners'
            | 'method';
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'audienceSolutions';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'whySolutions';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'connectedCtaSolutions';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqSolutions';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        note: string;
        tags: {
          label: string;
          id?: string | null;
        }[];
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroStartups';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        layoutVariant: 'iconCards' | 'numberedCards';
        items: {
          number?: string | null;
          icon?: ('lightbulb' | 'presentation' | 'rocket' | 'arrowRight') | null;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'valueStartups';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailedCards' | 'simpleCards';
        whenRelevantLabel?: string | null;
        resultLabel?: string | null;
        items: {
          title: string;
          description: string;
          whenRelevant?: string | null;
          result?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'deliverablesStartups';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailedCards' | 'simpleCards';
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        items: {
          situation: string;
          explanation?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'situationsStartups';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          icon: 'fileText' | 'gitBranch' | 'layout' | 'play' | 'palette' | 'package';
          title: string;
          support: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'artifactsStartups';
      }
    | {
        eyebrow: string;
        title: string;
        steps: {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'processStartups';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          icon: 'zap' | 'refreshCw' | 'users' | 'target';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'efficiencyStartups';
      }
    | {
        eyebrow: string;
        title: string;
        conceptBadgeLabel: string;
        challengeLabel: string;
        clarifiedLabel: string;
        preparedLabel: string;
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        items: {
          title: string;
          challenge: string;
          clarified: string;
          prepared: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'conceptsStartups';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaStartups';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqStartups';
      }
    | {
        eyebrow: string;
        titlePrefix: string;
        titleAccent: string;
        titleSuffix?: string | null;
        description: string;
        descriptionSecondary: string;
        partnerTags: {
          label: string;
          id?: string | null;
        }[];
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroAgencies';
      }
    | {
        title: string;
        description: string;
        pillars: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'partnersClarificationAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          title: string;
          text: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'audienceAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailed' | 'compact';
        items: {
          icon?: ('presentation' | 'palette' | 'layout' | 'send') | null;
          title: string;
          problem?: string | null;
          whenRelevant?: string | null;
          whyHelpful?: string | null;
          text?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'valueAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailed' | 'compact';
        useCaseLabel?: string | null;
        outputLabel?: string | null;
        items: {
          title: string;
          explanation: string;
          useCase: string;
          output?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectsAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'connected' | 'compact';
        steps: {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        markers: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'processAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          icon:
            | 'fileText'
            | 'gitBranch'
            | 'map'
            | 'layoutGrid'
            | 'smartphone'
            | 'mousePointer'
            | 'palette'
            | 'send'
            | 'fileCheck';
          title: string;
          support: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'artifactsAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailed' | 'compact';
        items: {
          title: string;
          description?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        description?: string | null;
        layoutVariant: 'grid' | 'carousel';
        challengeLabel: string;
        clarifiedLabel: string;
        preparedLabel: string;
        viewAllLabel: string;
        viewAllPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        items: {
          badge: string;
          title: string;
          challenge: string;
          clarified: string;
          prepared: string;
          imageSource?: ('url' | 'upload') | null;
          imageAlt?: string | null;
          imageUrl?: string | null;
          imageMedia?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'conceptsAgencies';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqAgencies';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        descriptionSecondary: string;
        trustLabels: {
          label: string;
          id?: string | null;
        }[];
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        descriptionSecondary?: string | null;
        rightTitle: string;
        pillars?:
          | {
              label: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        deliveryElements: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'positioningBlockPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        contextLine?: string | null;
        forWhomLabel: string;
        includesLabel: string;
        packages: {
          packageKey: string;
          title: string;
          subtitle: string;
          price: string;
          priceNote: string;
          timeline: string;
          forWhom: string;
          includes: {
            label: string;
            id?: string | null;
          }[];
          primaryButtonLabel: string;
          primaryPageKey:
            | 'home'
            | 'solutions'
            | 'pricing'
            | 'get-proposal'
            | 'concepts'
            | 'for-startups'
            | 'for-partners'
            | 'method';
          secondaryLinkLabel: string;
          secondaryPageKey:
            | 'home'
            | 'solutions'
            | 'pricing'
            | 'get-proposal'
            | 'concepts'
            | 'for-startups'
            | 'for-partners'
            | 'method';
          featured?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'packageCardsPricing';
      }
    | {
        eyebrow: string;
        title: string;
        situationLabel: string;
        solutionLabel: string;
        recommendedLabel: string;
        buttonLabel: string;
        items: {
          condition: string;
          problem: string;
          solution: string;
          package: string;
          packageKey: 'framing' | 'prototype' | 'partner';
          pageKey:
            | 'home'
            | 'solutions'
            | 'pricing'
            | 'get-proposal'
            | 'concepts'
            | 'for-startups'
            | 'for-partners'
            | 'method';
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'choosingGuidePricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        layoutVariant: 'visuals' | 'simple';
        topLinkLabel?: string | null;
        topLinkPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        items: {
          name: string;
          subtitle: string;
          visual?: ('structure' | 'scenarios' | 'screen-map' | 'prototype' | 'design-system' | 'dev-materials') | null;
          id?: string | null;
        }[];
        footerNote?: string | null;
        footerLinkLabel?: string | null;
        footerLinkPageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deliverablesPreviewPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        descriptionSecondary: string;
        quote: string;
        points: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'priceExplanationPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        steps: {
          icon: string;
          step: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'noCallCtaPricing';
      }
    | {
        eyebrow: string;
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'finalCtaPricing';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        descriptionSecondary: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroMethod';
      }
    | {
        eyebrow: string;
        title: string;
        layoutVariant: 'detailed' | 'grid';
        steps: {
          number: string;
          title: string;
          subtitle?: string | null;
          description: string;
          duration?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'stepsMethod';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'deliverablesMethod';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaMethod';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        supportLine?: string | null;
        reassuranceItems: {
          icon: 'clock' | 'fileText' | 'shield' | 'users';
          text: string;
          id?: string | null;
        }[];
        brandParagraph: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroProposal';
      }
    | {
        title: string;
        description: string;
        items: {
          icon: 'layers' | 'users' | 'building2' | 'arrowRightLeft';
          title: string;
          description: string;
          id?: string | null;
        }[];
        supportPoints?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustProposal';
      }
    | {
        title: string;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqProposal';
      }
    | {
        introCopy: {
          key: string;
          value: string;
          id?: string | null;
        }[];
        introProcessSteps: {
          icon: 'target' | 'users' | 'layers' | 'arrowUpRight' | 'arrowUpLeft';
          title: string;
          description: string;
          id?: string | null;
        }[];
        wizardCopy: {
          key: string;
          value: string;
          id?: string | null;
        }[];
        wizardStepLabels: {
          value: string;
          id?: string | null;
        }[];
        projectTypes: {
          value: string;
          label: string;
          description?: string | null;
          id?: string | null;
        }[];
        projectGoals: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        teamTypes: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        complexityFlags: {
          value: string;
          id?: string | null;
        }[];
        materialsOptions: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        referenceLinksMode: 'enabled' | 'disabled';
        timelineOptions: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        budgetOptions: {
          value: string;
          label: string;
          id?: string | null;
        }[];
        summaryResults: {
          value: string;
          id?: string | null;
        }[];
        uploadCopy: {
          key: string;
          value: string;
          id?: string | null;
        }[];
        successCopy: {
          key: string;
          value: string;
          id?: string | null;
        }[];
        successHomePageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        successPricingPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        successSteps: {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'proposalFlowProposal';
      }
    | {
        title: string;
        description: string;
        uploadButtonLabel: string;
        pricingButtonLabel: string;
        pricingPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'finalSupportProposal';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        supportLine: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        tags: {
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroConcepts';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        pillars: {
          icon: 'layers' | 'penTool' | 'arrowRight' | 'arrowLeft';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'introConcepts';
      }
    | {
        label: string;
        items: {
          anchorId: string;
          shortLabel: string;
          number: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'navConcepts';
      }
    | {
        anchorId: string;
        sectionNumber: string;
        categoryLabel: string;
        title: string;
        intro: string;
        imageSource?: ('url' | 'upload') | null;
        imageAlt?: string | null;
        image?: string | null;
        imageMedia?: (number | null) | Media;
        challengeLabel: string;
        challenge: string;
        structuredLabel: string;
        structured: string;
        deliveredLabel: string;
        delivered: string;
        suitableForLabel: string;
        suitableFor: string;
        captionLabel: string;
        captionStudioLabel: string;
        layout: 'imageLeft' | 'imageRight';
        ctaLabel: string;
        ctaPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        id?: string | null;
        blockName?: string | null;
        blockType: 'conceptSectionConcept';
      }
    | {
        eyebrow: string;
        title: string;
        description: string;
        items: {
          icon: 'search' | 'layers' | 'monitor' | 'fileText';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyConcepts';
      }
    | {
        title: string;
        description: string;
        primaryButtonLabel: string;
        primaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        secondaryButtonLabel: string;
        secondaryPageKey:
          | 'home'
          | 'solutions'
          | 'pricing'
          | 'get-proposal'
          | 'concepts'
          | 'for-startups'
          | 'for-partners'
          | 'method';
        footerNote: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaConcepts';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-files".
 */
export interface ProposalFile {
  id: number;
  alt?: string | null;
  sourceType: 'proposal-upload';
  request?: (number | null) | ProposalRequest;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-requests".
 */
export interface ProposalRequest {
  id: number;
  mode: 'wizard' | 'upload';
  locale: 'ru' | 'en' | 'ar';
  name?: string | null;
  email?: string | null;
  company?: string | null;
  role?: string | null;
  region?: string | null;
  phone?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  links?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  uploadedAssets?: (number | ProposalUploadAsset)[] | null;
  files?: (number | ProposalFile)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-upload-assets".
 */
export interface ProposalUploadAsset {
  id: number;
  filename: string;
  mimeType: string;
  filesize: number;
  storageKey: string;
  downloadUrl: string;
  uploadToken: string;
  status: 'pending' | 'uploaded' | 'attached';
  request?: (number | null) | ProposalRequest;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'proposal-files';
        value: number | ProposalFile;
      } | null)
    | ({
        relationTo: 'proposal-upload-assets';
        value: number | ProposalUploadAsset;
      } | null)
    | ({
        relationTo: 'proposal-requests';
        value: number | ProposalRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  routeType?: T;
  pageKey?: T;
  slug?: T;
  internalName?: T;
  metaTitle?: T;
  metaDescription?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              titleRows?:
                | T
                | {
                    segments?:
                      | T
                      | {
                          text?: T;
                          tone?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              description?: T;
              supportingNote?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              desktopBadgeLabel?: T;
              mobileBadgeLabel?: T;
              desktopImageSource?: T;
              desktopImageAlt?: T;
              desktopImageUrl?: T;
              desktopImage?: T;
              mobileImageSource?: T;
              mobileImageAlt?: T;
              mobileImageUrl?: T;
              mobileImage?: T;
              id?: T;
              blockName?: T;
            };
        valueHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    variant?: T;
                    icon?: T;
                    kicker?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoWalkthroughHome?:
          | T
          | {
              displayMode?: T;
              eyebrow?: T;
              title?: T;
              subheadline?: T;
              videoLabel?: T;
              durationLabel?: T;
              metaBadges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              timeline?:
                | T
                | {
                    number?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              highlightsTitle?: T;
              highlights?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              ctaTitle?: T;
              ctaSubtext?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              videoSource?: T;
              videoUrl?: T;
              videoFile?: T;
              posterSource?: T;
              posterUrl?: T;
              posterMedia?: T;
              posterAlt?: T;
              id?: T;
              blockName?: T;
            };
        deliverablesHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        audienceHome?:
          | T
          | {
              sectionId?: T;
              eyebrow?: T;
              title?: T;
              problemLabel?: T;
              solutionLabel?: T;
              resultLabel?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              items?:
                | T
                | {
                    title?: T;
                    problem?: T;
                    solution?: T;
                    result?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        conceptsHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              challengeLabel?: T;
              structuredLabel?: T;
              deliveredLabel?: T;
              viewConceptsLabel?: T;
              conceptsPageKey?: T;
              previousAriaLabel?: T;
              nextAriaLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    badge?: T;
                    challenge?: T;
                    structured?: T;
                    delivered?: T;
                    imageSource?: T;
                    imageAlt?: T;
                    imageUrl?: T;
                    imageMedia?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        methodHome?:
          | T
          | {
              sectionId?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    details?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricingHome?:
          | T
          | {
              sectionId?: T;
              eyebrow?: T;
              title?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              featuredBadge?: T;
              items?:
                | T
                | {
                    name?: T;
                    price?: T;
                    timeline?: T;
                    description?: T;
                    featured?: T;
                    includes?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        proposalHome?:
          | T
          | {
              sectionId?: T;
              title?: T;
              description?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        samplePreviewHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    imageSource?: T;
                    alt?: T;
                    imageUrl?: T;
                    imageMedia?: T;
                    id?: T;
                  };
              bottomNote?: T;
              id?: T;
              blockName?: T;
            };
        trustHome?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqHome?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        finalCtaHome?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        heroSolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              note?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              imageSource?: T;
              imageAlt?: T;
              imageUrl?: T;
              imageMedia?: T;
              id?: T;
              blockName?: T;
            };
        positioningIntroSolutions?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gridSolutions?:
          | T
          | {
              eyebrow?: T;
              learnMoreLabel?: T;
              items?:
                | T
                | {
                    anchorId?: T;
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        detailsSolution?:
          | T
          | {
              whenRelevantLabel?: T;
              whatWeClarifyLabel?: T;
              whatClientReceivesLabel?: T;
              items?:
                | T
                | {
                    anchorId?: T;
                    title?: T;
                    intro?: T;
                    whenRelevant?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    whatWeClarify?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    whatClientReceives?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    primaryButtonLabel?: T;
                    primaryPageKey?: T;
                    secondaryButtonLabel?: T;
                    secondaryPageKey?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        clientArtifactsSolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    imageSource?: T;
                    alt?: T;
                    imageUrl?: T;
                    imageMedia?: T;
                    id?: T;
                  };
              bottomNote?: T;
              id?: T;
              blockName?: T;
            };
        audienceSolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              challengeLabel?: T;
              resultLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    challenge?: T;
                    result?: T;
                    ctaLabel?: T;
                    ctaPageKey?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whySolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        connectedCtaSolutions?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        faqSolutions?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              note?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        valueStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              layoutVariant?: T;
              items?:
                | T
                | {
                    number?: T;
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        deliverablesStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              whenRelevantLabel?: T;
              resultLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    whenRelevant?: T;
                    result?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        situationsStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              items?:
                | T
                | {
                    situation?: T;
                    explanation?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        artifactsStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    support?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        efficiencyStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        conceptsStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              conceptBadgeLabel?: T;
              challengeLabel?: T;
              clarifiedLabel?: T;
              preparedLabel?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              items?:
                | T
                | {
                    title?: T;
                    challenge?: T;
                    clarified?: T;
                    prepared?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaStartups?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        faqStartups?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroAgencies?:
          | T
          | {
              eyebrow?: T;
              titlePrefix?: T;
              titleAccent?: T;
              titleSuffix?: T;
              description?: T;
              descriptionSecondary?: T;
              partnerTags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        partnersClarificationAgencies?:
          | T
          | {
              title?: T;
              description?: T;
              pillars?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        audienceAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        valueAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    problem?: T;
                    whenRelevant?: T;
                    whyHelpful?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectsAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              useCaseLabel?: T;
              outputLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    explanation?: T;
                    useCase?: T;
                    output?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              markers?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        artifactsAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    support?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        conceptsAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              layoutVariant?: T;
              challengeLabel?: T;
              clarifiedLabel?: T;
              preparedLabel?: T;
              viewAllLabel?: T;
              viewAllPageKey?: T;
              items?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    challenge?: T;
                    clarified?: T;
                    prepared?: T;
                    imageSource?: T;
                    imageAlt?: T;
                    imageUrl?: T;
                    imageMedia?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaAgencies?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        faqAgencies?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        heroPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              descriptionSecondary?: T;
              trustLabels?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        positioningBlockPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              descriptionSecondary?: T;
              rightTitle?: T;
              pillars?:
                | T
                | {
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              deliveryElements?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        packageCardsPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              contextLine?: T;
              forWhomLabel?: T;
              includesLabel?: T;
              packages?:
                | T
                | {
                    packageKey?: T;
                    title?: T;
                    subtitle?: T;
                    price?: T;
                    priceNote?: T;
                    timeline?: T;
                    forWhom?: T;
                    includes?:
                      | T
                      | {
                          label?: T;
                          id?: T;
                        };
                    primaryButtonLabel?: T;
                    primaryPageKey?: T;
                    secondaryLinkLabel?: T;
                    secondaryPageKey?: T;
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        choosingGuidePricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              situationLabel?: T;
              solutionLabel?: T;
              recommendedLabel?: T;
              buttonLabel?: T;
              items?:
                | T
                | {
                    condition?: T;
                    problem?: T;
                    solution?: T;
                    package?: T;
                    packageKey?: T;
                    pageKey?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        deliverablesPreviewPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              layoutVariant?: T;
              topLinkLabel?: T;
              topLinkPageKey?: T;
              items?:
                | T
                | {
                    name?: T;
                    subtitle?: T;
                    visual?: T;
                    id?: T;
                  };
              footerNote?: T;
              footerLinkLabel?: T;
              footerLinkPageKey?: T;
              id?: T;
              blockName?: T;
            };
        priceExplanationPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              descriptionSecondary?: T;
              quote?: T;
              points?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        noCallCtaPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    step?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        faqPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        finalCtaPricing?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        heroMethod?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              descriptionSecondary?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              id?: T;
              blockName?: T;
            };
        stepsMethod?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              layoutVariant?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    subtitle?: T;
                    description?: T;
                    duration?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        deliverablesMethod?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaMethod?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
        heroProposal?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              supportLine?: T;
              reassuranceItems?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    id?: T;
                  };
              brandParagraph?: T;
              id?: T;
              blockName?: T;
            };
        trustProposal?:
          | T
          | {
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              supportPoints?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqProposal?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        proposalFlowProposal?:
          | T
          | {
              introCopy?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              introProcessSteps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              wizardCopy?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              wizardStepLabels?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              projectTypes?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              projectGoals?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              teamTypes?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              complexityFlags?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              materialsOptions?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              referenceLinksMode?: T;
              timelineOptions?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              budgetOptions?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              summaryResults?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              uploadCopy?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              successCopy?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              successHomePageKey?: T;
              successPricingPageKey?: T;
              successSteps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        finalSupportProposal?:
          | T
          | {
              title?: T;
              description?: T;
              uploadButtonLabel?: T;
              pricingButtonLabel?: T;
              pricingPageKey?: T;
              id?: T;
              blockName?: T;
            };
        heroConcepts?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              supportLine?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        introConcepts?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              pillars?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        navConcepts?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    anchorId?: T;
                    shortLabel?: T;
                    number?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        conceptSectionConcept?:
          | T
          | {
              anchorId?: T;
              sectionNumber?: T;
              categoryLabel?: T;
              title?: T;
              intro?: T;
              imageSource?: T;
              imageAlt?: T;
              image?: T;
              imageMedia?: T;
              challengeLabel?: T;
              challenge?: T;
              structuredLabel?: T;
              structured?: T;
              deliveredLabel?: T;
              delivered?: T;
              suitableForLabel?: T;
              suitableFor?: T;
              captionLabel?: T;
              captionStudioLabel?: T;
              layout?: T;
              ctaLabel?: T;
              ctaPageKey?: T;
              id?: T;
              blockName?: T;
            };
        whyConcepts?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaConcepts?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButtonLabel?: T;
              primaryPageKey?: T;
              secondaryButtonLabel?: T;
              secondaryPageKey?: T;
              footerNote?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-files_select".
 */
export interface ProposalFilesSelect<T extends boolean = true> {
  alt?: T;
  sourceType?: T;
  request?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-upload-assets_select".
 */
export interface ProposalUploadAssetsSelect<T extends boolean = true> {
  filename?: T;
  mimeType?: T;
  filesize?: T;
  storageKey?: T;
  downloadUrl?: T;
  uploadToken?: T;
  status?: T;
  request?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposal-requests_select".
 */
export interface ProposalRequestsSelect<T extends boolean = true> {
  mode?: T;
  locale?: T;
  name?: T;
  email?: T;
  company?: T;
  role?: T;
  region?: T;
  phone?: T;
  payload?: T;
  links?:
    | T
    | {
        url?: T;
        id?: T;
      };
  uploadedAssets?: T;
  files?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  brandName: string;
  brandTagline: string;
  navigation: {
    label: string;
    pageKey:
      | 'home'
      | 'solutions'
      | 'pricing'
      | 'get-proposal'
      | 'concepts'
      | 'for-startups'
      | 'for-partners'
      | 'method';
    id?: string | null;
  }[];
  proposalButtonLabel: string;
  mobileLanguageLabel: string;
  menuAriaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  variant: 'dark' | 'light';
  brandName: string;
  brandTagline: string;
  description: string;
  brandEmail?: string | null;
  columns: {
    type: 'links' | 'cta';
    title: string;
    links?:
      | {
          label: string;
          pageKey?:
            | (
                | 'home'
                | 'solutions'
                | 'pricing'
                | 'get-proposal'
                | 'concepts'
                | 'for-startups'
                | 'for-partners'
                | 'method'
              )
            | null;
          href?: string | null;
          anchor?: string | null;
          id?: string | null;
        }[]
      | null;
    body?: string | null;
    buttonLabel?: string | null;
    buttonPageKey?:
      | ('home' | 'solutions' | 'pricing' | 'get-proposal' | 'concepts' | 'for-startups' | 'for-partners' | 'method')
      | null;
    buttonHref?: string | null;
    id?: string | null;
  }[];
  bottomTextTemplate: string;
  bottomLinks?:
    | {
        label: string;
        pageKey?:
          | (
              | 'home'
              | 'solutions'
              | 'pricing'
              | 'get-proposal'
              | 'concepts'
              | 'for-startups'
              | 'for-partners'
              | 'method'
            )
          | null;
        href?: string | null;
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  brandName?: T;
  brandTagline?: T;
  navigation?:
    | T
    | {
        label?: T;
        pageKey?: T;
        id?: T;
      };
  proposalButtonLabel?: T;
  mobileLanguageLabel?: T;
  menuAriaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  variant?: T;
  brandName?: T;
  brandTagline?: T;
  description?: T;
  brandEmail?: T;
  columns?:
    | T
    | {
        type?: T;
        title?: T;
        links?:
          | T
          | {
              label?: T;
              pageKey?: T;
              href?: T;
              anchor?: T;
              id?: T;
            };
        body?: T;
        buttonLabel?: T;
        buttonPageKey?: T;
        buttonHref?: T;
        id?: T;
      };
  bottomTextTemplate?: T;
  bottomLinks?:
    | T
    | {
        label?: T;
        pageKey?: T;
        href?: T;
        anchor?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}